export const SocketEventTypes = {
  JoinRoom: 'join-room',
  CountdownStarted: 'countdown-started',
  RoomLocked: 'room-locked',
  RoomJoined: 'room-joined',
  SelectLetter: 'select-letter',
  LetterSelected: 'letter-selected',
  EndTurn: 'end-turn',
  StartTurn: 'start-turn',
  CountdownTick: 'tick',
  ResetTimer: 'reset-timer',
  LeaveRoom: 'leave-room',
  PlayerEliminated: 'player-eliminated',
  RoundStarted: 'round-started',
  RoundEnded: 'round-ended',
  SetIsInTextMode: 'set-is-in-text-mode',
  GameEnded: 'game-ended',
}
