on:
  workflow_dispatch:

jobs:
  test:
    name: test front-end
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: test front-end
      run: |
        npm install
        CI=true npm test
    
