on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    name: test front-end
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20
    - name: test front-end
      run: |
        npm install
        CI=true npm test
    
