name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: test front-end
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: test front-end
        run: |
          npm install
          CI=true npm test
  build:
    name: build front-end
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: build front-end
        run: |
          npm install
          SERVER=$QUIK_SERVER_URL BUILD_PATH=./fe-build npm run build
      - name: Upload front-end build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fe-build
          path: fe-build
          retention-days: 5
  build_tag_push_to_ghcr:
    runs-on: self-hosted
    needs: [test, build]
    steps:
      - name: Download front-end build artifacts
        uses: actions/download-artifact@v4
        with:
          name: fe-build
          path: /home/campbellrehu/dev/actions-runner/_work/quik/quik/
          
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/campbell-rehu
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/campbell-rehu/quik:latest
