name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: test front-end
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: test front-end
        run: |
          npm install
          CI=true npm test
  build_tag_push_to_ghcr:
    runs-on: self-hosted
    needs: [test]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/campbell-rehu
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/campbell-rehu/quik:latest
